name: ArmorStandGenerator
version: '1.0'
main: me.drknxt.armorStandGenerator.ArmorStandGenerator
api-version: '1.21'
authors: [ DrkNxt ]
description: Plugin letting you generate custom armor stands using a simple to understand GUI
commands:
  armorstand:
    description: Open armor stand creation menu
    usage: /<command>
    aliases:
      - as
